# Generated by Django 4.1.7 on 2023-04-03 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webie', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
