# Generated by Django 4.1.7 on 2023-04-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publication_date', models.DateField()),
                ('pages', models.IntegerField()),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
