# Generated by Django 4.1.7 on 2023-04-03 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apie', '0002_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={},
        ),
    ]
