# Generated by Django 4.1.7 on 2023-04-13 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apie', '0004_product_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
